name: flutter_sms
description: A Flutter plugin to Send SMS and MMS on iOS and Android. If iMessage is enabled it will send as iMessage on iOS. This plugin must be tested on a real device on iOS.
version: 2.1.1
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/fluttercommunity/flutter_sms
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.2
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^1.0.1
  flutter_user_agent: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_sms
        pluginClass: FlutterSmsPlugin
      ios:
        pluginClass: FlutterSmsPlugin
      # macos:
      #   pluginClass: FlutterSmsPlugin
     # web:
       # pluginClass: FlutterSmsPlugin
       # fileName: flutter_sms_web.dart
